"""
Django settings for base project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-tx*$*xfmwjwgzi5&3oy&c+o5&jj$a@)(-&=zgc%c_(v#)5spx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
LOCAL = True
# DEBUG_PROPAGATE_EXCEPTIONS = True

DOMAIN_URL = 'http://127.0.0.1:8000'
COMPANI = 'compani name'

DB_PASS = 'acJL>Z3!X2i&&e'
DB_USR = 'ibhfrwld_root'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'customer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'base.urls'

TEMPLATE_URL =os.path.join(BASE_DIR, 'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_URL, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                  'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'base.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ********************************************************************
#                        Data Base Config
# ********************************************************************


if LOCAL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }

    }
else:
    DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': 'ibhfrwld_database',
                'USER': DB_USR,
                'PASSWORD': DB_PASS,
                'HOST': 'localhost',
                'PORT': '',
                'CONN_MAX_AGE': 500
            }
        }



# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


#********************************************************************
#                    Statics & Media
#********************************************************************

STATIC_DIR = os.path.join(BASE_DIR, 'statics')
STATIC_ROOT = os.path.join(BASE_DIR, 'static-server')
STATIC_URL = '/statics/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'statics'),
]

# Media folder for database media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, '/media')

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



# *************************************************
#               user auth model
# *************************************************


AUTH_USER_MODEL = 'user.User'



# ************************************************************
#                            login url
# ************************************************************


LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# LOGIN_URL = '/auth/login/google-oauth2/'




# *************************************************
#                    backend auth
# *************************************************



AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    # 'social_core.backends.google.GoogleOAuth2',
)



# ****************************************************************
#                        Social Config
# ****************************************************************

# AIzaSyCkRtN_qk_qttC0G37Zv7j-dVqfhDJilGY


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = ''
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = ''
SOCIAL_AUTH_URL_NAMESPACE = 'social'

# id =

# secred =


# **********************************************
#               Email                          *
#***********************************************

# ****  example ***

# google settings
# SMTP Host: smtp.gmail.com
# SMTP Port: 587
# SSL Protocol: OFF
# TLS Protocol: ON
# SMTP Username: (your Gmail username)
# SMTP Password: (your Gmail password)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'cuentaigc9@gmail.com'
EMAIL_HOST_PASSWORD = 'Palabra123'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

